import { Header } from "../components/landing/Header";
import { ShieldCheck, Sparkles, Users } from "lucide-react";

const About = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="container mx-auto px-4 pt-28 pb-16 max-w-3xl">
        <div className="text-center mb-12">
          <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            About ZeroPlagiarism
          </h1>
          <p className="text-muted-foreground text-lg">
            We help students, writers, and educators verify originality and
            maintain academic integrity in an age of AI-generated content.
          </p>
        </div>

        <div className="grid gap-8 md:grid-cols-3 mb-16">
          <div className="text-center">
            <div className="w-12 h-12 mx-auto mb-4 rounded-lg bg-primary/10 flex items-center justify-center">
              <ShieldCheck className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-semibold text-foreground mb-2">Our Mission</h3>
            <p className="text-sm text-muted-foreground">
              Making originality verification accessible and reliable for
              everyone, from students to professional writers.
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 mx-auto mb-4 rounded-lg bg-primary/10 flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-semibold text-foreground mb-2">Our Approach</h3>
            <p className="text-sm text-muted-foreground">
              We combine linguistic analysis and machine learning to detect
              AI-generated text and potential plagiarism with clear, actionable
              results.
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 mx-auto mb-4 rounded-lg bg-primary/10 flex items-center justify-center">
              <Users className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-semibold text-foreground mb-2">Who We Serve</h3>
            <p className="text-sm text-muted-foreground">
              Students, educators, content teams, and anyone who needs
              confidence that a piece of writing is original.
            </p>
          </div>
        </div>

        <div className="prose prose-neutral max-w-none text-foreground">
          <h2 className="text-xl font-semibold mb-3">Our Story</h2>
          <p className="text-muted-foreground leading-relaxed mb-6">
            ZeroPlagiarism started as a response to a simple, growing problem:
            as AI writing tools became widespread, it got harder to tell
            whether a piece of text was written by a person or generated by a
            model &mdash; and harder still to know whether it was original at
            all. We built a set of tools that combine AI-detection scoring and
            plagiarism checking in one place, so that verifying a document's
            authenticity doesn't require juggling multiple disconnected
            services.
          </p>
          <h2 className="text-xl font-semibold mb-3">What We Value</h2>
          <p className="text-muted-foreground leading-relaxed">
            Transparency in how our tools work, respect for the people whose
            writing we're analyzing, and a commitment to giving useful,
            actionable results rather than black-box scores with no
            explanation.
          </p>
        </div>
      </main>
    </div>
  );
};

export default About;